import puppeteer from 'puppeteer'
const email = 'epdarnell+test@gmail.com', name = 'EdTest Test',
    anon = 'epdarnell+anon@gmail.com'
import { url, setPage, setDebug, scp, rm, mv, waitForFile, uc1, tt, hover, token, unsub } from './utils.mjs'

let browser, page
beforeAll(async () => {
    //browser = await puppeteer.launch({ headless: false })
    browser = await puppeteer.launch({ headless: "new" })
    page = await browser.newPage()
    setPage(page)
    setDebug(false)
    await page.evaluateOnNewDocument(() => {
        // make anti-spam and background image predictable
        Math.random = () => 0.5
        window._test = true
    })
})

afterAll(async () => {
    jest.restoreAllMocks()
    await browser.close()
})

describe('LoggedOut', () => {
    //beforeEach(async () => await page.goto('about:blank'))
    afterEach(async () => setDebug(false))
    test('Home', async () => {
        const css = await waitForFile('combined.css')
        await scp('combined', css, '.css')
        await page.goto(url)
        const home = await page.$eval('#root', h => h.innerHTML)
        await scp('home', home)
    })
    test('Pages', async () => {
        await page.goto(url)
        const nav = ['details', 'results', 'home']
        for (const link of nav) {
            await page.click(`a[href="${link}"]`)
            await page.waitForFunction(() => !document.querySelector('#loading'))
            await page.waitForFunction(v => document.querySelector('#nav_page').innerText === v, {}, uc1(link))
            const pg = await page.$eval('#root', h => h.innerHTML)
            await scp(link, pg)
        }
    })

    test('Contact', async () => {
        rm('Contact.email')
        await page.goto(url)
        await hover('TT_contact', 'contact us')
        await page.click('[id^="TT_contact"]')
        await page.waitForSelector('#contact_form')
        const pg = await page.$eval('[id^="popup_TT_contact"]', h => h.innerHTML)
        await scp('contact', pg)
        await hover('IN_send', 'complete the form', 'disabled')

        await page.type('[id^="IN_name"]', 'Puppeteer Pages')
        await page.type('[id^="IN_email"]', email)
        await page.type('[id^="IN_subject"]', 'Contact')
        await page.type('[id^="IN_message"]', 'Test message')
        await hover('IN_send', 'please tick the middle box', 'disabled')

        await page.click('[id^="IN_spam2"]')
        await hover('IN_send', 'send', 'primary')
        await page.click('[id^="IN_send"]')
        await tt('contact', 'Message sent.', 'success')
        const m = await waitForFile('Contact.email')
        await scp('Contact', m, '.email')
    })

    test.only('LoginU', async () => {
        await rm('Login.email')
        await page.goto(url)
        await page.click('[id^="TT_user"]')
        await page.waitForSelector('#login_form')
        await page.type('[id^="IN_email"]', anon)
        await page.click('[id^="IN_spam2"]')
        await page.click('[id^="IN_login"]')
        await tt('user', 'Login link emailed.', 'success')
        const m = await waitForFile('Login.email')
        await scp('Login', m, '.email', 'U')
    })
})

describe('LoggedIn', () => {
    beforeEach(async () => await page.goto('about:blank'))
    afterEach(async () => setDebug(false))

    test('Login', async () => {
        await unsub(email, false)
        rm('Login.email')
        await page.goto(url)
        await hover('TT_user', 'login or register')
        await page.click('[id^="TT_user"]')
        await page.waitForSelector('#login_form')
        await hover('TT_close', 'close')
        await page.click('[id^="TT_close"]')
        await page.waitForFunction(() => !document.querySelector('#login_form'));
        await page.click('[id^="TT_user"]')
        await page.waitForSelector('#login_form')
        const pg = await page.$eval('[id^="popup_TT_user"]', h => h.innerHTML)
        await scp('login', pg)
        await hover('IN_login', 'enter your email', 'disabled')
        await page.type('[id^="IN_email"]', email)
        await hover('IN_login', 'please tick the middle box', 'disabled')
        await page.click('[id^="IN_spam2"]')
        await hover('IN_login', 'login by email', 'primary')
        await page.click('[id^="IN_login"]')
        await tt('user', 'Login link emailed.', 'success')
        const m = await waitForFile('Login.email')
        await scp('Login', m, '.email')
    })

    test('Unsub', async () => {
        await unsub(email, false)
        rm('Unsubscribe.email')
        rm('Unsub.email')
        await page.goto(url + '/unsubscribe#' + await token(email))
        await page.waitForSelector('#unsub')
        await hover('IN_unsub', 'Confirm Unsubscribe', 'primary')
        await page.type('[id^="IN_reason"]', 'Pupeteer test')
        await page.click('[id^="IN_unsub"]')
        await tt('user', 'Unsubscribed.')
        const un = await waitForFile('Unsubscribe.email')
        await scp('Unsubscribe', un, '.email')
        const ua = await waitForFile('Unsub.email')
        await scp('Unsub', ua, '.email')
    })
    test('ContactUn', async () => {
        rm('Contact.email')
        await unsub(email, true)
        await page.goto(url + '#' + await token(email))
        await page.waitForSelector('[id^="TT_contact"]')
        await hover('TT_user', name)
        await hover('TT_contact', 'contact us')
        await page.click('[id^="TT_contact"]')
        await page.waitForSelector('[id^="popup_TT_contact"]')
        await hover('IN_send', 'complete the form', 'disabled')
        await page.type('[id^="IN_subject"]', 'Contact')
        await hover('IN_send', 'complete the form', 'disabled')
        await page.type('[id^="IN_message"]', 'Test User message')
        await hover('IN_send', 'send', 'primary')
        await page.click('[id^="IN_send"]')
        await tt('contact', 'Error Sending (unsubscribed).', 'error')
    })
    test('Sub', async () => {
        rm('Subscribe.email')
        rm('Sub.email')
        await unsub(email, true)
        await page.goto(url + '#' + await token(email))
        await page.waitForSelector('[id^="TT_user"]')
        await hover('TT_user', name)
        await page.click('[id^="TT_user"]')
        await page.waitForSelector('#subscribe')
        await page.click('[id^="IN_sub"]')
        await tt('user', 'Subscribed.', 'success')
        const m = await waitForFile('Subscribe.email')
        await scp('Subscribe', m, '.email')
        const am = await waitForFile('Sub.email')
        await scp('Sub', am, '.email')
    })
    test('ContactU', async () => {
        rm('Contact.email')
        await unsub(email, false)
        await page.goto(url + '#' + await token(email))
        await page.waitForSelector('[id^="TT_contact"]')
        await hover('TT_user', name)
        await hover('TT_contact', 'contact us')
        await page.click('[id^="TT_contact"]')
        await page.waitForSelector('[id^="popup_TT_contact"]')
        await hover('IN_send', 'complete the form', 'disabled')
        await page.type('[id^="IN_subject"]', 'Contact')
        await hover('IN_send', 'complete the form', 'disabled')
        await page.type('[id^="IN_message"]', 'Test User message')
        await hover('IN_send', 'send', 'primary')
        await page.click('[id^="IN_send"]')
        await tt('contact', 'Message sent.', 'success')
        const m = await waitForFile('Contact.email')
        await scp('Contact', m, '.email', 'U')
    })
    test('UsubU', async () => {
        await unsub(email, false)
        await page.goto(url + '#' + await token(email))
        await page.waitForSelector('[id^="TT_user"]')
        await hover('TT_user', name)
        await page.click('[id^="TT_user"]')
        await page.waitForSelector('[id^="popup_TT_user"]')
        await hover('TT_unsubscribe', 'unsubscribe')
        await page.click('[id^="TT_unsubscribe"]')
        await page.waitForSelector('#unsub')
        await hover('IN_unsub', 'Confirm Unsubscribe', 'primary')
        await page.type('[id^="IN_reason"]', 'Puppeteer User')
        await page.click('[id^="IN_unsub"]')
        await tt('user', 'Unsubscribed.')
    })
    test('SubU', async () => {
        rm('Subscribe.email')
        rm('Sub.email')
        await unsub(email, true)
        await page.goto(url + '/subscribe#' + await token(email))
        await page.waitForSelector('#subscribe')
        await page.click('[id^="IN_sub"]')
        await tt('user', 'Subscribed.', 'success')
        const m = await waitForFile('Subscribe.email')
        await scp('Subscribe', m, '.email')
        const am = await waitForFile('Sub.email')
        await scp('Sub', am, '.email')
    })
    test('SubU2', async () => {
        await unsub(email, false)
        await page.goto(url + '/subscribe#' + await token(email))
        await tt('user', 'Subscribed.', 'success')
    })
})
