const year = '2024',
    links = {
        pool: { tip: 'Hatch End pool website', href: 'https://www.everyoneactive.com/centre/hatch-end-swimming-pool/' },
        fields: { tip: 'Google maps link', href: 'https://www.google.com/maps/place/Uxbridge+Rd,+Pinner+HA5+4EA' },
        jetstream: { tip: 'Jetstream triathlon club', href: 'https://jetstreamtri.com' },
        british_triathlon: { tip: 'British Triathlon website', href: 'https://www.britishtriathlon.org' },
        pinner_camera_club: { tip: 'Pinner Camera Club', href: 'https://www.pinnercameraclub.co.uk/' },
        rules: { tip: 'British Triathlon rules', href: 'https://www.britishtriathlon.org/competitionrules' },
        age8_16: { tip: `age on 31 December ${year} not now or race date` },
        enter_now: { tip: 'entries open 15 Dec 2023', href: '', class: 'enter-button disabled' },
        adult_run: { tip: 'Adult run course', href: 'AdultRunCourse.pdf' },
        adult_cycle: { tip: 'Adult cycle course', href: 'AdultCycleMap.pdf' },
        adult_briefing: { tip: 'Adult briefing', href: 'AdultBriefing.pdf' },
        junior_briefing: { tip: 'Junior briefing', href: 'JuniorBriefing.pdf' },
        junior_cycle_run: { tip: 'Junior cycle & run courses', href: 'JuniorRaceCourses.pdf' },
        event_permit: { tip: 'British Triathlon Event Permit', href: 'event_permit.pdf' },
        race_membership: { tip: 'British Triathlon Race Pass', href: 'https://www.britishtriathlon.org/race-pass' },
        novice_guide: { tip: 'Novice Guide', href: 'NoviceGuide.pdf' },
        site_map: { tip: 'Site map', href: 'SiteMap.pdf' },
        book: { href: 'https://bookwhen.com/jetstreamtraining', tip: 'Jetstream booking system' },
        minet_park: { href: 'https://hillingdoncyclecircuit.org.uk/location/', tip: 'Hillingdon Cycle Cicuit' },
        approved: { tip: '<image src="/permitted_2023.jpg" width="128"/>', theme: 'light' },
        organised: { tip: '<image src="/permitted_organiser_2023.jpg" width="128"/>', theme: 'light' },
        atw: { tip: 'Active Training World', href: 'https://www.atwevents.co.uk/' },
        hatch_end_scouts: { tip: '1st Hatch End Scout Group', href: 'https://www.harrowscouts.org.uk/1st-hatch-end' },
        everyone_active: { tip: 'Everyone Active', href: 'https://www.everyoneactive.com/' },
        harrow_council: { tip: 'Harrow Council', href: 'https://www.harrow.gov.uk/' }
    }
export { links }